command:
  - "python"
  - "app.py"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: LAKEBASE_PROJECT_ID
    value: many-model-forecasting-advanced
  - name: LAKEBASE_DATABASE_NAME
    value: databricks_postgres
  - name: LAKEBASE_BRANCH
    value: production
