command:
  - "python"
  - "app.py"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: LAKEBASE_INSTANCE_NAME
    value: mmf-forecast-serving
  - name: LAKEBASE_DATABASE_NAME
    value: postgres
